/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package funciones.trigonométricas;

import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class Trigonométricas extends javax.swing.JFrame {

    /**
     * Creates new form Trigonométricas
     */
    public Trigonométricas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text_Angulo = new javax.swing.JTextField();
        ComboBox_Funciones = new javax.swing.JComboBox();
        Button_Run = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Ingrese angulo");

        Text_Angulo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        ComboBox_Funciones.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ComboBox_Funciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Funciones", "Cos", "Sin", "Tan" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Text_Angulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(ComboBox_Funciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Angulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_Funciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_Run.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Button_Run.setText("Run");
        Button_Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Button_Run)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_Run)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void trigonometria(){
        //Declaramos las variables
        double angulo,res;
        String funcion;
        
        //Condición para validar el Text_Angulo si está vacío
        if (Text_Angulo.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Ingrese un ángulo");
            //Coloca el Focus en el Text_Angulo
            Text_Angulo.requestFocus();
        }else{
            /*Función que convierte en un tipo double el valor que se ingrese por 
            el Text_Angulo y lo almacena en la variable ángulo */
            angulo = Double.parseDouble(Text_Angulo.getText());
            //Método para extraer los Item seleccionado en el ComboBox
            funcion = ComboBox_Funciones.getSelectedItem().toString();
            /*Condición que evalúa la variable función si es igual a las funciones 
          seleccionada en el ComboBox */
            if ("Funciones".equals(funcion)) {
                JOptionPane.showMessageDialog(null,"Selecccione una de las funciones");
            }else{
                /* 
              Switch case es una estructura de control permitiéndonos controlar
              las opciones que escojamos por el ComboBox
             */
               switch(funcion){
                   case "Cos":
                       /* Método que saca el Coseno del dato que este almacenado 
                      en la varia ángulo y lo almacena en la variable res */
                      //res = Math.cos(Math.toRadians(angulo));
                        res = (Math.cos (angulo * Math.PI / 180) );
                       //res = Math.cos(angulo*2.0*Math.PI/360.0);
                       JOptionPane.showMessageDialog(null,"El cos del ángulo" +
                               angulo + " es " + res);
                       break;
                       
                   case "Sin":
                       /* Método que saca el Seno del dato que este almacenado 
                      en la varia ángulo y lo almacena en la variable res */
                      res = Math.sin(angulo*2.0*Math.PI/360.0);
                       JOptionPane.showMessageDialog(null,"El Seno del ángulo" +
                               angulo + " es " + res);
                       break;
                           
                   case "Tan":
                       /* Método que saca el Tangente del dato que este almacenado 
                      en la varia ángulo y lo almacena en la variable res */
                      res = Math.tan(angulo*2.0*Math.PI/360.0);
                       JOptionPane.showMessageDialog(null,"El Tangente del ángulo" +
                               angulo + " es " + res);
                       break;
               }
            }
        }
    }
    private void Button_RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RunActionPerformed
        trigonometria();
    }//GEN-LAST:event_Button_RunActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trigonométricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trigonométricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trigonométricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trigonométricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trigonométricas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Run;
    private javax.swing.JComboBox ComboBox_Funciones;
    private javax.swing.JTextField Text_Angulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
